Ajout des documents AGO 2023
zestedesavoir/documents-association pull request #32
Opened 2023-07-01 11:38 UTC by entwanne

2023-07-03 19:18 UTC, Rockaround reviewed
Presque uniquement des typos

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +L'équipe éditoraiable est composée de 16 membres (sgble l'a quittée récemment) et l'équipe communication de 4 (2 départs non remplacés).
Éditoriale

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +6 étudiants de l'INP de Bordeaux encadrés par Philippe et Yoann Mollard ont travaillé sur plusieurs grands projets du site, notamment le système de labels et la refonte du système de recherche. Elast
Nom de famille de Philippe à ajouter ?

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +Il y a eu peu d'adhésions entre janvier et décembre 2022, mais les membres se sont rattrapés en 2023. Le montant de cotisation est maintenant différencié (25€ ou 10€) versus 10€ précédemment.
Vs 25 précédemment, non ?

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [Étienne] On n'a pas eu de dépenses liées aux événements (remborusement de frais, location, places) ?
Remboursement

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +Sur les recettes, on conserve la même tarficiation différenciée des adhésions. 4 membres sur 22 ont cotisé au tarif réduit. Il n'y a pas eu de membre d'honneur (exonération à l'adhésion).
Tarification

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [Amaury] Les patrons et pages de contenus sont des projets en chantier mais seulement au stade de maquettes.
Patreons

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [Remarque de Florent] Ce serait bien que l'on vote cette orientation je trouve, qu'on en fasse ensuite un bilan l'an prochain et qu'on aajuste éventuellement.
Ajuste

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [Amaury] J'ai le sentiment que des gens demandent des choses mais qu'il n'y a plus personne au moment de les réaliser. Le rapport d'activité de l'AGO a par exemple été réalisé seul (aide de Phili
Il voudraient des événements / plus d'événements

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [François] En effet si on ne suit que le site on passe à côté de choses communiquées uniquement sur discord. Attention au burnout associatif, c'est un gros problème. Si vous sentez que ça ne va p
On s'est beaucoup

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +S'il devient officiel, se pose aussi la question d'embrasser pleinenement la plateforme qui peut être intéressant pour cibler certaines audiences (notamment les gens nés après 2005).
Pleinement la plateforme, ce qui peut

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [Luciano] Même ressenti que de fait il y a des libertés permises sur discord qui ne passeraient absolument pas sur le forum
Je ne comprends pas le début de la phrase.

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [François] Si on officialise, où vons les boosts ? Est-ce qu'on inciterait les gens à en faire ?
Vont

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_AGO.md
> +> - [Jérome] On pourraitt aussi avoir un bot de modération.
Pourrait

2023-07-03 19:18 UTC, Rockaround commented on 2023/2023-06-24_PV_RCA.md
> +Antoine se propose de rester secrétaire si personne d'autre ne veut du poste.
Antoine R.

2023-07-03 19:19 UTC, AmauryCarrade commented on 2023/2023-06-24_PV_RCA.md
> +- Antoine Rozo (entwanne)
fsdfsdf

2023-07-03 21:11 UTC, AmauryCarrade commented on 2023/2023-06-24_PV_AGO.md
> +> - [Luciano] Même ressenti que de fait il y a des libertés permises sur discord qui ne passeraient absolument pas sur le forum
On peut la comprendre en

> J'ai le même ressenti : en effet, il y a des libertés…

2023-07-03 21:12 UTC, AmauryCarrade commented on 2023/2023-06-24_PV_AGO.md
> +Sur les recettes, on conserve la même tarficiation différenciée des adhésions. 4 membres sur 22 ont cotisé au tarif réduit. Il n'y a pas eu de membre d'honneur (exonération à l'adhésion).
Sois dit en passant : l'erreur a été prononcée lors de l'AGO, mais c'était cinq, pas quatre, tarifs réduits. (Le dernier était la veille de l'AGO, peut-être pour ça qu'il n'a pas été vu.)

2023-07-08 07:18 UTC, entwanne commented on 2023/2023-06-24_PV_AGO.md
> +6 étudiants de l'INP de Bordeaux encadrés par Philippe et Yoann Mollard ont travaillé sur plusieurs grands projets du site, notamment le système de labels et la refonte du système de recherche. Elast
Son nom est précisé au début du document

2023-07-08 07:25 UTC, entwanne commented
C'est corrigé

2023-07-16 13:32 UTC, AmauryCarrade commented
Je fais la revue dés que possible ! Faut-il que je le considère comme urgent ou puis-je laisser de côté jusqu'à la fin de la semaine prochaine ?

2023-07-16 14:25 UTC, entwanne commented
Non rien d'urgent, les documents sont déjà pour les personnes intéressées, regarde quand tu as le temps.

2023-08-17 10:23 UTC, AmauryCarrade requested changes
J'ai enfin eu le temps de relire
J'ai repéré quelques typos ou soucis de clartés, mais dans l'ensemble ça me semble pas mal tout ça

2023-08-17 10:23 UTC, AmauryCarrade commented on 2023/2023-06-24_PV_AGO.md
> +* Jérome Tanghe (Carrade) ;
```suggestion
* Jérome Tanghe (Deuchnord) ;
```

2023-08-17 10:23 UTC, AmauryCarrade commented on 2023/2023-06-24_PV_AGO.md
> +* Nathanaël Langlois (ÉtoileFilante) ;
```suggestion
* Nathanaël Langlois (Étoile Filante) ;
```

2023-08-17 10:23 UTC, AmauryCarrade commented on 2023/2023-06-24_PV_AGO.md
> +* Reprise avec Melcore des activités d'artragis : énigmes, cycles et répétitions (jeu du trou-trou), activité autour des graphs (article d'Aaby sur l'ordre d'habillage), cryptologie.
```suggestion
* Reprise par Melcore et Amaury des activités d'artragis : énigmes, cycles et répétitions (jeu du trou-trou), activité autour des graphs (article d'Aaby sur l'ordre d'habillage), cryptologie.
```

2023-08-17 10:23 UTC, AmauryCarrade commented on 2023/2023-06-24_PV_AGO.md
> +firm1: J'ai l'impression que « sonder » avant de se lancer sur les projet peut créer l'effet « ZdS » avec beaucoup de débats et que l'on n'avance jamais.
Réponse de @firm1 mal transcrite ou adresse de @enzzc à ce dernier ? C'est peu clair en lisant, je trouve.

2023-08-20 14:21 UTC, entwanne commented on 2023/2023-06-24_PV_AGO.md
> +6 étudiants de l'INP de Bordeaux encadrés par Philippe et Yoann Mollard ont travaillé sur plusieurs grands projets du site, notamment le système de labels et la refonte du système de recherche. Elast
J'ai ajouté le nom pour la cohérence

2023-08-20 14:21 UTC, entwanne commented on 2023/2023-06-24_PV_AGO.md
> +firm1: J'ai l'impression que « sonder » avant de se lancer sur les projet peut créer l'effet « ZdS » avec beaucoup de débats et que l'on n'avance jamais.
Corrigé (c'était un propos de firm1)

2023-08-24 12:20 UTC, AmauryCarrade approved these changes
Ça semble OK pour moi :)

2023-08-24 16:35 UTC, merged